name: UICoder
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023d=h04d1e81_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - appdirs==1.4.4
      - asttokens==2.4.1
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - filelock==3.13.1
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.41
      - huggingface-hub==0.20.2
      - idna==3.6
      - ipykernel==6.28.0
      - ipython==8.20.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - nltk==3.8.1
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - packaging==23.2
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.1.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.2
      - psutil==5.9.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.17.2
      - python-dateutil==2.8.2
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - regex==2023.12.25
      - requests==2.31.0
      - safetensors==0.4.1
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - sympy==1.12
      - tokenizers==0.13.3
      - torch==2.1.2
      - torchvision==0.16.2
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.1
      - transformers==4.33.1
      - triton==2.1.0
      - typing-extensions==4.9.0
      - urllib3==2.1.0
      - wandb==0.16.2
      - wcwidth==0.2.13
prefix: /data02/users/lz/miniconda3/envs/UICoder
